
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 08:02:45 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 12;
  public static final int READ = 8;
  public static final int PLUS = 15;
  public static final int SEMI = 22;
  public static final int CHAR = 6;
  public static final int LEFTPAR = 19;
  public static final int END = 4;
  public static final int SWITCH = 10;
  public static final int RIGHTPAR = 20;
  public static final int WRITE = 9;
  public static final int ID = 13;
  public static final int PROGRAM = 2;
  public static final int SUB = 17;
  public static final int BEGIN = 3;
  public static final int EQUALS = 27;
  public static final int COMMA = 23;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int DOTDOT = 21;
  public static final int DOT = 24;
  public static final int CONST = 14;
  public static final int CASE = 11;
  public static final int error = 1;
  public static final int INTEGER = 5;
  public static final int REAL = 7;
  public static final int MUL = 16;
  public static final int RIGHTCURLY = 26;
  public static final int LEFTCURLY = 25;
}

